### ISSUE TITLE
README with build and deploy instructions

### ISSUE THREAD

**Issue by bagelface** [gnars-dao/gnars-frontend#13]
As per discussion @sktbrd and I had at last Tech Pod meeting 16/01, we should include a README in this repo that includes at the very least the following info:

- Summary of the project
- Build instructions
- Deploy instructions

Of course, whoever is implementing this can feel free to get as fancy with it as possible.

**Comment by sktbrd** [comment]
Same thing for gnarsdotcom https://github.com/gnars-dao/gnarsdotcom/issues/4
