### ISSUE TITLE
Front End - Implement Migration Modal with Accompanying Banner

### ISSUE THREAD

**Issue by mulfdev** [gnars-dao/gnars-frontend#16]
### Description

Create a modal focused on informing users about the migration to Nouns Builder on the Base network, complemented by an accompanying banner.

* * *

### Changes

*   **Modal Implementation:** Develop a modal to detail the migration process to the Nouns Builder. The modal is the centerpiece of this update, designed to provide users with essential information regarding the transition.
    
*   **Banner Implementation:** Implemented an accompanying banner. This banner, following the site's color scheme, features a single line of copy with a word that triggers the modal.
    
*   **Local Storage Timing Logic:** Integrated a timing mechanism using local storage. This ensures the modal is shown to the user only once every 24 hours, respecting their experience and avoiding frequent interruptions.
    

* * *

### How to Test

1.  **Modal Display Logic:** Confirm that the modal pops up upon your first visit or after the 24-hour threshold has passed since the last viewing.
2.  **Banner Interaction:** Test the banner's functionality by clicking on the designated trigger word to ensure it correctly opens the modal.
3.  **Content Accuracy:** Review the modal and banner content for accurate information regarding the migration to the Nouns Builder.
4.  **Responsiveness:** Check the modal and banner on various devices and screen sizes for proper responsiveness and visibility.

**Comment by bagelface** [comment]
As discussed on tonight's Tech Pod call, this is a bountied issue estimated at 2 story points. It will be rewarded by 2 Gnars or 100 $USDC.

**Comment by asmattic** [comment]
> 3\. **content accuracy:** review the modal and banner content for accurate information regarding the migration to the nouns builder.

Is there a general process in place to request or collaborate on the copy/content? especially for this modal, as the details need to be 100% accurate.

**Comment by bagelface** [comment]
> > 3. **content accuracy:** review the modal and banner content for accurate information regarding the migration to the nouns builder.
> 
> Is there a general process in place to request or collaborate on the copy/content? especially for this modal, as the details need to be 100% accurate.
> 
> this is not a blocker for the implementation of the modal or banner. it could inform the design of the modal content section depending on the copy length necessary, as well as making sure the most important concept is communicated instantly for the likely majority of users that will not read every detail.

No formal process. If you have access to the Tech Pod you could just post in there what you're thinking and get a few other's opinions, but I don't think it has to be anything fancy. Maybe something like:

```
Gnars has been migrated to Base!

We're updating this site to be fully operational on Base. In the meantime, auctions and governance are live on the new site. If you owned Gnars on mainnet, they've been airdropped to your wallet on Base (check your hidden folder on OpenSea).

Stay tuned. Stay gnarly. ⌐◨-◨\m/
```

**Comment by webbdays** [comment]
Hi,
I WOULD LIKE TO WORK ON THIS.

**Comment by bagelface** [comment]
> I would like to work on this issue.

Hi, this issue has already been claimed by https://github.com/asmattic . We'll have more issues with bounties coming up though, so stay tuned
