### ISSUE TITLE
Frontend - Update all webapp dependencies to their latest major versions

### ISSUE THREAD

**Issue by bagelface** [gnars-dao/gnars-frontend#18]
### Description

Update all package dependencies used by the webapp to their latest major version. This includes, but isn't limited to, "chakra-ui", "next", "wagmi", "eslint", and "storybook" for example.

"Major version" refers to the [semantic versioning](https://semver.org/) definition of the word term.

* * *

### Changes

*   **Update major versions of dependencies:** Update the all dependencies used by the webapp to be the latest major version of that package.
*   **Update major versions of dependencies:** Update the all "devDependencies" used by the webapp to be the latest major version of that package.
*   **Update webapp code to work with updated packages:** Make the necessary code changes required so that the webapp continues to function as expected with the new versions of the packages. There should be no regression in functionality.

* * *

### Acceptance Criteria

1. All dependencies are updated to their latest major version.
2. There must be no regression in site functionality.
3. Build and run steps remain simple and consistent with the README.
4. The site is builds and deploys on Vercel.

### Bounty Details
This issue is rewarded by a bounty upon completion. It was estimated by the Gnars Tech Pod as **3 story points** which equates to **4 Gnars or 200 $USDC**.

**Comment by asmattic** [comment]
I'll take this one. I've already started testing since I knew it was coming up

**Comment by webbdays** [comment]
can i?

**Comment by sktbrd** [comment]
I offer myself for that one too

**Comment by bagelface** [comment]
> can i please?

We give priority on bountied issues to people who are members of Gnars DAO. If you'd like to join us in the Discord, we'd be happy to have you: https://discord.com/invite/XBeZuMxmst

**Comment by bagelface** [comment]
The "wagmi" package was excluded from this issue because it was determined to be out of scope. It has been migrated to a new issue: https://github.com/gnars-dao/gnars-frontend/issues/30
