### ISSUE TITLE
Frontend - Update webapp treasury viewer to show Base treasury and multi-sig balances

### ISSUE THREAD

**Issue by bagelface** [gnars-dao/gnars-frontend#21]
### Description 🗒️

Update webapp treasury viewer to show Base treasury and multi-sig balances.

<img width="313" alt="Screenshot 2024-04-12 at 7 54 08 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/87501783/9e9183fe-a72d-43fb-af69-d6e2361743ae">

Gnars Base treasury: https://basescan.org/address/0x72ad986ebac0246d2b3c565ab2a1ce3a14ce6f88
Gnars Base multi-sig: https://basescan.org/address/0x9a670ea90b3683ca6d90572b4f5cdbdd81a191fd

* * *

### Details 🏗️

* **Update treasury balances:** Update the treasury viewer to display Base balances of ETH, USDC, and Gnars tokens for the DAO treasury.
* **Update multi-sig balances:** Update the treasury viewer to display Base balances of ETH, USDC, and Gnars tokens for the Gnars multi-sig.
* **(OPTIONAL) Add $SENDIT balance:** This is not a requirement to claim the bounty, but optionally you can add the [$SENDIT](https://basescan.org/token/0xBa5B9B2D2d06a9021EB3190ea5Fb0e02160839A4?a=0x72ad986ebac0246d2b3c565ab2a1ce3a14ce6f88) balance to both views. Gami transferred a significant portion of the supply to the Gnars treasury and it has a nice valuation at the moment.

* * *

### Acceptance Criteria ☑️

1. All of the changes described in the "Details" section above are implemented and tested.
2. Code is clear, clean, and properly documented.
3. UI changes are sensible and non-regressive.

* * *

### Bounty Details 💰
This issue is rewarded by a bounty upon completion. It was estimated by the Gnars Tech Pod as **3 story points** which equates to **4 Gnars or 200 $USDC**.

**Comment by r4topunk** [comment]
Heyyy, whats up??
I made some updates to my PR #24 related to this Issue!
