### ISSUE TITLE
Update proposal viewer to show Base proposals and details

### ISSUE THREAD

**Issue by bagelface** [gnars-dao/gnars-frontend#22]
### Description 🗒️

Update webapp [proposal viewer](https://www.gnars.wtf/dao) to show Base proposals and details.

* * *

### Details 🏗️

* **Update list of proposals:** Update the proposal [list view](https://www.gnars.wtf/dao) to show all the proposals made on the Base contracts.
* ~~**Update proposal details view:** Update the proposal [detail viewer](https://www.gnars.wtf/dao/proposals/38) to show the details of any proposal made on the Base contracts.~~ Replaced by new issue https://github.com/gnars-dao/gnars-frontend/issues/46 
* **Preserve mainnet proposal viewer code:** Do not remove code, such as subgraphs, used for viewing mainnet proposals. We have plans to include an viewer for mainnet proposals alongside Base proposals to preserver the history of the DAO.

* * *

### Acceptance Criteria ☑️

1. All of the changes described in the "Details" section above are implemented and tested.
2. Code is clear, clean, and properly documented.
3. UI changes are sensible and non-regressive.

**Comment by sktbrd** [comment]
Lets add markdown handlers for youtube, zora and other popular iframes that time

**Comment by bagelface** [comment]
> Lets add markdown handlers for youtube, zora and other popular iframes that time

Definitely a nice thing to add, though I would advocate to creating a separate bounty ticket for that. I think it would bloat this one up too much.

**Comment by bagelface** [comment]
Issue mentioned in "nouns infra" Discord that may affect this issue:
<img width="854" alt="Screenshot 2024-05-08 at 7 30 33 PM" src="https://github.com/gnars-dao/gnars-frontend/assets/87501783/42f9dd7a-4650-4bc3-9dc8-8a76dec30659">
https://discord.com/channels/1133102918829101136/1133102919416287254/1237696543994282006

**Comment by reubenstein** [comment]
I've already done a lot of the BASE groundwork for this ticket while working on #23, so I'd be happy to start this once after I finish

**Comment by sktbrd** [comment]
@0xMillz I think the list checks , right ?
