### ISSUE TITLE
Treasury Display Missing USDC

### ISSUE THREAD

**Issue by benbodhi** [gnars-dao/gnars-frontend#6]
Since we've now got USDC as the bulk of the treasury, the balance indicator at the top of the site should be updated to display the USDC as well.

Also might be worth switching the url it links out to. It currently goes to the main address page on etherscan, but tokenholdings might be better suited?
https://etherscan.io/tokenholdings?a=0xa1B74d2280966A89AC7e0F3A8bc5f0867C776d98

**Comment by sktbrd** [comment]
https://github.com/gnars-dao/gnars-frontend/pull/10

**Comment by sktbrd** [comment]
> #10

I think we can close that one @volkyeth
